# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iQT-TXh17pGyJ_cmrGRlJgOFNRypJK1b
"""

import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn.metrics import accuracy_score, confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns

data = {
    'outlook': ['sunny', 'sunny', 'overcast', 'rainy', 'rainy'],
    'humidity': ['high', 'high', 'high', 'normal', 'normal'],
    'windy': ['false', 'true', 'false', 'false', 'true'],
    'play': ['no', 'no', 'yes', 'yes', 'no']
}
df = pd.DataFrame(data)

print("Original DataFrame:")
print(df)
print("-" * 30)

X = df.drop('play', axis=1)
y = df['play']

label_encoders = {}
X_encoded = X.copy()

for col in X.columns:
    le = LabelEncoder()
    X_encoded[col] = le.fit_transform(X[col])
    label_encoders[col] = le

le_target = LabelEncoder()
y_encoded = le_target.fit_transform(y)

print("Encoded Features (X_encoded):")
print(X_encoded)
print("-" * 30)

clf = DecisionTreeClassifier(max_depth=2, random_state=42)

clf.fit(X_encoded, y_encoded)

plt.figure(figsize=(10, 6))
plot_tree(
    clf,
    feature_names=X.columns,
    class_names=le_target.classes_,
    filled=True,
    rounded=True
)
plt.title("Decision Tree Visualization")
plt.show()

y_pred = clf.predict(X_encoded)

accuracy = accuracy_score(y_encoded, y_pred)
print(f"Accuracy: {accuracy:.1%}")

cm = confusion_matrix(y_encoded, y_pred)

print("Confusion Matrix (Text):")
print(f"[[TN FP]\n [FN TP]] = \n{cm}")

plt.figure(figsize=(6, 4))
sns.heatmap(
    cm,
    annot=True,
    fmt='d',
    cmap='Blues',
    xticklabels=le_target.classes_,
    yticklabels=le_target.classes_
)
plt.title('Confusion Matrix')
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.show()