# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15UUxeoPxRkW15hACa0e2LyY35fZR12gZ
"""

import pandas as pd
import numpy as np

raw_data = {
    'student_ID': ['S1', 'S2', 'S3', 'S4', 'S5'],
    'name': ['Danniella Fenton', 'Ryder Storey', 'Bryce Jensen', 'Ed Bernal', 'Kwame Morin'],

}

df_student = pd.DataFrame(raw_data)

df_student.head()

marks = {
    'student_ID': ['S1', 'S2', 'S3', 'S4', 'S5'],
     'math_marks': [100 ,70 , 80 , np.nan, 300],
    'physics_marks': [100 , 70 , 80 , 90 , 300]
}

df_marks =  pd.DataFrame(marks)

df_marks.head()

median_math = df_marks['math_marks'].median()
df_marks['math_marks'] = df_marks['math_marks'].fillna(median_math)
print(f"mean math score {median_math:.2f}")



median_physics = df_marks['physics_marks'].median()
df_min = df_marks[df_marks['physics_marks'] > 100]
df_min
# df.loc [df['physics_marks'] > 100, 'physics_marks'] = median_physics
# print(f"median physics score {median_physics:.2f}")

df_merge = pd.merge(df_student, df_marks, on='student_ID', how='right')
median_math = df_merge['math_marks'].median()
df_merge.loc[df_merge['math_marks'] > 100, 'math_marks'] = median_math
df_merge.loc[df_merge['math_marks'] < 100, 'math_marks'] = median_math
print(f"Updated df_merge with marks > 100 set to median:")
display(df_merge)

merge_data = pd.merge(df_student, df_marks, on='student_ID', how='right')
print(merge_data)

df_merge = pd.DataFrame(merge_data)

df_merge.head()

df = df_merge.drop_duplicates()

df_merge.loc[df_merge['math_marks'] > 100, 'math_marks'] = median_math
print(f"Updated df_merge after replacing marks < 100 with median:")
display(df_merge)

median_physics = df_merge['physics_marks'].median()
df_merge.loc[df_merge['physics_marks'] > 100, 'physics_marks'] = median_physics
print(f"Updated df_merge after processing physics_marks (median: {median_physics:.2f}):")
display(df_merge)

all_scores = df_merge[['math_marks', 'physics_marks']]
min_score = all_scores.min().min()
max_score = all_scores.max().max()
print(f"Minimum score: {min_score}")
print(f"Maximum score: {max_score}")

# Normalize 'math_marks' to a 0-1 range
min_math_current = df_merge['math_marks'].min()
max_math_current = df_merge['math_marks'].max()

# Avoid division by zero if all values are the same
if max_math_current == min_math_current:
    df_merge['math_marks'] = 0.0
else:
    df_merge['math_marks'] = (df_merge['math_marks'] - min_math_current) / (max_math_current - min_math_current)

# Normalize 'physics_marks' to a 0-1 range
min_physics_current = df_merge['physics_marks'].min()
max_physics_current = df_merge['physics_marks'].max()

# Avoid division by zero if all values are the same
if max_physics_current == min_physics_current:
    df_merge['physics_marks'] = 0.0
else:
    df_merge['physics_marks'] = (df_merge['physics_marks'] - min_physics_current) / (max_physics_current - min_physics_current)

print("df_merge after min-max normalization to [0, 1]:")
display(df_merge)